var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                    * * * *                                                     ",
   "                   xxxxxxxxx                                                    ",
   "    @                                                                           ",
   "   xxxx                              xxx                                        ",
   "                         o  o   xxx                   o o                       ",
   "        xxxx            xxxxxx                       xxxxx                      ",
   "  x            o o o o                   x                                      ",
   "  x           xxxxxxxxx                  x                                      ",
   "  x                                      x                           * * *      ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                          xxxxxxxx    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       o o                            ",
   "                                                 xxx!!!!!!!!xxxxxxx             ",
   "                                                   xxxxxxxxxx                   ",
   "                                                                                ",
   "        *                                 o o                                   ",
   "       xxx                     o  o      xxxxx                                  ",
   "       !                      xxxxxx                                            ",
   "       !        o o o o o                                                       ",
   "       !      xxxxxxxxxxxx!!!!                                                  ",
   "       !                                                     w                  ",
   "       !                                               xxxxxxxxxxxx             ",
   "       !                     o o o                                              ",
   "       !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                   ",
   "   @               +                                       xx         xxxxxxxxxxxxxxx          x   ",
   " xxxxx        xxxxxxxxxxx                                 xx         xx             x          x   ",
   "  xx           xx                                        xx      o   xx             x   o      x   ",
   "   xx o o       xx                                      xx      xxxxx               x  xxx     x   ",
   "    xxxxxxx      xx                                    xx o        xx               x          x   ",
   "     xx       o o xx                                  xxxxx      xx                 x      o   x   ",
   "      xx      xxxxxxx                                xx         xx                  x     xxx  x   ",
   "       xx           xx                              xx       o xx                   x          x   ",
   "        xx o o       xx          o o o             xx      xxxxx                    x    o     x   ",
   "         xxxxxxx      xx        xxxxxxx           xx o       xx                     x   xxx    x   ",
   "          xx           xx                        xxxxx      xx                      x          x   ",
   "           xx      o o  xx                      xx         xx                       x          x   ",
   "            xx     xxxxxxxx                    xx         xx                        x          x   ",
   "             xx           xx                  xx       o xx                         x      o   x   ",
   "              xx           xx                xx      xxxxx                          x     xxx  x   ",
   "               xx                                      xx                           x          x   ",
   "                xx                                    xx                            x   o      x   ",
   "                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                             x  xxx     x   ",
   "                                                                                                   ",
   "               o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o   ",
   "              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                   ",
   "      +                  +                          +                     +                     x   ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x   ",
   "        x                                                                                       x   ",
   "        x                                                                                       x   ",
   "        x  w                                                                                    x   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!x   ",
   "                                                                                                x   "],


   ["                                                                ",
    "     @                                                          ",
    "                                                                ",
    "                                                                ",
    "                                                          |     ",
    "           +++   o o                 o o o o o            |     ",
    "      xxxxxxxxxxxxxxx             xxxxxxxxxxxxxx          |     ",
    "                                                          |     ",
    "                                                          |     ",
    "   !!!!!!!!!!        !!!!!!!!!!!!!!!                      |     ",
    "                                                          |     ",
    "                                                          |     ",
    "                                                          |     ",
    "        o o     *  *     o o                              |     ",
    "       xxxxxx           xxxxxx                            |     ",
    "                                        o o o o o o o o   |     ",
    "                                      xxxxxxxxxxxxxxxxxxxxx     ",
    "           !!!!!!!!!!!!!!!!!!!!!!!!!!!!                   |     ",
    "                                                          |     ",
    "    o o o o o o o o o o o o o o o o o o o o o             |     ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           |     ",
    "                                                          |     ",
    "                                                          |     ",
    "                      *                  *                |     ",
    "              *                  *               *        |     ",
    "         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
    "                                                                ",
    "      +++                                                       ",
    "   xxxxxxxxx                                                    ",
    "                                                                ",
    "                                                                ",
    "                                  w                             ",
    "                        xxxxxxxxxxxxxx                          "],

    ["                                                               ",
     "                                                               ",
     "                                        yy        yy           ",
     "                                        yy        yy           ",
     "     x   x     xxx     x   x        yy                 yy      ",
     "     x   x    x   x    x   x          yyy            yyy       ",
     "      xxxx    x   x    x   x             yyyyyyyyyyyy          ",
     "         x    x   x    x   x                                   ",
     "      xxxx     xxx      xxx                x                   ",
     "                                           x                   ",
     "                                           x                   ",
     "                   x  x  x   x   x xxx     x                   ",
     "                   x  x  x       xx   x    x                   ",
     "                   x  x  x   x   x    x    x                   ",
     "                   x  x  x   x   x    x                        ",
     "                   x  x  x   x   x    x    x                   ",
     "                    xx xx    x   x    x    x                   ",
     "                                                               ",
     "                                                               "]
  ];

  if (typeof module != "undefined" && module.exports)
    module.exports = GAME_LEVELS;
